Build Avoidance
Purpose:
   Reduce build times after a repo sync by pulling in pre-generated
srpms and rpms and other build products created by a local reference build.

Usage:
  repo sync
  generate-cgcs-centos-repo.sh ...
  populate_downloads.sh ...
  build-pkgs --build-avoidance [--build-avoidance-user <user> \
     --build-avoidance-host <addr> --build-avoidance-dir <dir>]

Reference builds:
- A server performs a regular (daily?), automated builds using
  existing methods. Call these the reference builds.

- The builds are timestamped, and preserved for some time. (weeks?)
  The MY_WORKSPACE directory for the build shall have a common root
  directory, and a leaf directory that is a time stamp of format
  YYYY-MM-DD_hh-mm-ss.
  e.g.
  MY_WORKSPACE=/localdisk/loadbuild/jenkins/StarlingX/2018-07-19_11-30-21

- A build CONTEXT is captured, consisting of the SHA of each and every
  git that contributed to the build.

- For each package built, a file shall capture he md5sums of all the
  source code inputs to the build of that package.

- All these build products are accessible locally (e.g. a regional
  office) via rsync (other protocols can be added later).  ssh
  is also required to run remote query commands on the reference build.

- Location of the reference build can be specified via command line, or
  defaults can be put in $MY_REPO/local-build-data/build_avoidance_source.
  The local-build-data directory is gitignored by stx-root and so can be
  customized for local needs.
  e.g.
  cat $MY_REPO/local-build-data/build_avoidance_source
  BUILD_AVOIDANCE_USR="jenkins"
  BUILD_AVOIDANCE_HOST="stx-build-server.myco.com"
  BUILD_AVOIDANCE_DIR="/localdisk/loadbuild/jenkins/StarlingX"

Notes:
- Build avoidance is only used if requested.
- Build avoidance does not necessarily use the latest reference build.
  It compares the git context of all available reference builds vs your
  own git context, and chooses the most recent for which you gits have
  all the conent.  i.e. all your gits will be same or newer than that
  used by the reference build.  This also meens that some packages might
  still need to be rebuilt after the download step.
- Normally build avoidance remembers the last download context and will only
  consider reference builds newer than the last download.   You can reset
  using 'build-pkgs --build-avoidance --clear' to erase the download history.
  When might this matter to me?  If you change to an old branch that
  hasn't been synced recently and want to build in that context.
- The primary assumtion of Build Avoidance is that it is faster to
  download packages than to build them.  This is typically true of a
  good LAN, but likely not true of a WAN. This is why we emphasize the
  local nature of your reference build server.

Also in this update:
- reworked context generation to be relative to 'dirname $MY_REPO'
- Moved md5sum calculation to a common file, and fixed case where
  symlinks where canonacalized to paths outside of $MY_REPO.
  We'll make an exception to canonacalization to keep paths
  relative to $MY_REPO.
- In future other functions could be moved to the common file.

Story: 2002835
Task: 22754
Change-Id: I757780190cc6063d0a2d3ad9d0a6020ab5169e99
Signed-off-by: Scott Little <scott.little@windriver.com>

diff --git a/build-tools/build-pkgs-parallel b/build-tools/build-pkgs-parallel
--- a/build-tools/build-pkgs-parallel
+++ b/build-tools/build-pkgs-parallel
@@ -1,10 +1,22 @@
 #!/bin/bash
 
+#
+# Copyright (c) 2018 Wind River Systems, Inc.
+#
+# SPDX-License-Identifier: Apache-2.0
+#
+
+#
+# Build first src.rpms, then rpms, from source, or from a downloaded tarball
+# or src.rpm plus our additional patches.
+#
 # This program is a wrapper around build-srpms-parallel and build-rpms-parallel
+#
 
 BUILD_PKGS_PARALLEL_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}" )" )"
 
 source "${BUILD_PKGS_PARALLEL_DIR}/git-utils.sh"
+source "${BUILD_PKGS_PARALLEL_DIR}/build-avoidance-utils.sh"
 source "${BUILD_PKGS_PARALLEL_DIR}/spec-utils"
 
 
@@ -13,14 +25,15 @@ usage () {
     echo "Usage: "
     echo "   Create source and Binary rpms:"
     echo "   Build optimizations (--no-descendants, --no-required, --no-build-info,"
-    echo "   --no-autoclean) are not recommended for the first build after a clone/pull,"
-    echo "   nor the final build prior to creating an iso or patch, but can be used"
-    echo "   for intermediate builds.  i.e. while debugging compilation failures." 
-    echo "      build-pkgs-parallel [--no-descendants] [--no-required] [--no-build-info] [--no-autoclean] [--careful] [--formal] [ list of package names ]"
+    echo "   --no-autoclean, --no-build-avoidance) are not recommended for the first build"
+    echo "   after a clone/pull, nor the final build prior to creating an iso or patch,"
+    echo "   but can be used for intermediate builds."
+    echo "   i.e. while debugging compilation failures."
+    echo "      build-pkgs-parallel [--build-avoidance | --no-build-avoidance] [--no-descendants] [--no-required] [--no-build-info] [--no-autoclean] [--careful] [--formal] [ list of package names ]"
     echo ""
     echo "   Delete source rpms, and the directories associated with it's creation:"
     echo "   Note: does not clean an edit environment"
-    echo "      build-pkgs-parallel --clean [ list of package names ]"
+    echo "      build-pkgs-parallel --clean [--build-avoidance | --no-build-avoidance] [ list of package names ]"
     echo ""
     echo "   Extract an src.rpm into a pair of git trees to aid in editing it's contents,"
     echo "   one for source code and one for metadata such as the spec file."
@@ -39,15 +52,20 @@ usage () {
 HELP=0
 CLEAN_FLAG=0
 EDIT_FLAG=0
+APPEND_LOG_FLAG=0
+BUILD_AVOIDANCE_FLAG=0
 STD_BUILD=1
 RT_BUILD=1
 INSTALLER_BUILD=0
 
+export BUILD_AVOIDANCE_URL=""
+
+
 # read the options
-TEMP=$(getopt -o h --long parallel,rt,std,installer,edit,no-meta-patch,no-descendants,no-required,no-build-info,no-autoclean,formal,careful,help,clean -n 'build-pkgs-parallel' -- "$@")
+TEMP=$(getopt -o h --long parallel,rt,std,installer,edit,build-avoidance,no-build-avoidance,build-avoidance-dir:,build-avoidance-host:,build-avoidance-user:,build-avoidance-day:,no-meta-patch,no-descendants,no-required,no-build-info,no-autoclean,formal,careful,help,clean,append-log -n 'build-pkgs-parallel' -- "$@")
 if [ $? -ne 0 ]; then
     usage
-    exit 0
+    exit 1
 fi
 eval set -- "$TEMP"
 
@@ -55,8 +73,21 @@ eval set -- "$TEMP"
 EXTRA_ARGS_COMMON=""
 EXTRA_ARGS_SRPM=""
 EXTRA_ARGS_RPM=""
+
+export BUILD_AVOIDANCE_OVERRIDE_DIR=""
+export BUILD_AVOIDANCE_OVERRIDE_HOST=""
+export BUILD_AVOIDANCE_OVERRIDE_USR=""
+export BUILD_AVOIDANCE_DAY=""
+
 while true ; do
     case "$1" in
+        --append-log)     APPEND_LOG_FLAG=1 ; shift ;;
+        --build-avoidance) BUILD_AVOIDANCE_FLAG=1 ; shift ;;
+        --no-build-avoidance) BUILD_AVOIDANCE_FLAG=0 ; shift ;;
+        --build-avoidance-dir)  BUILD_AVOIDANCE_OVERRIDE_DIR=$2; shift 2 ;;
+        --build-avoidance-host)  BUILD_AVOIDANCE_OVERRIDE_HOST=$2; shift 2 ;;
+        --build-avoidance-user)  BUILD_AVOIDANCE_OVERRIDE_USR=$2; shift 2 ;;
+        --build-avoidance-day) BUILD_AVOIDANCE_DAY=$2; shift 2 ;;
         --no-descendants) EXTRA_ARGS_COMMON+=" --no-descendants" ; shift ;;
         --formal)         EXTRA_ARGS_COMMON+=" --formal" ; shift ;;
         --careful)        EXTRA_ARGS_RPM+=" --careful" ; shift ;;
@@ -125,11 +156,15 @@ trap my_sighup HUP
 trap my_sigabrt ABRT
 trap my_sigterm TERM
 
+# Note: For ease of parsing, a TARGETS list always begins and ends 
+# with a space.  An empty target list consistes of two spaces.
 TARGETS=" $@ "
-TARGETS_STD=" "
-TARGETS_RT=" "
-TARGETS_INSTALLER=" "
-TARGETS_MISC=" "
+EMPTY_TARGETS="  "
+
+TARGETS_STD="$EMPTY_TARGETS"
+TARGETS_RT="$EMPTY_TARGETS"
+TARGETS_INSTALLER="$EMPTY_TARGETS"
+TARGETS_MISC="$EMPTY_TARGETS"
 
 find_targets () {
    local centos_pkg_dirs=$1
@@ -199,14 +234,28 @@ find_targets () {
       fi
    done
 
-   echo "$RESULT"
+   if [ "$RESULT" == " " ]; then
+       echo "$EMPTY_LIST"
+   else
+       echo "$RESULT"
+   fi
    return 0
 }
 
+if [ $EDIT_FLAG -eq 1 ] || [ "x$TARGETS" != "x$EMPTY_TARGETS" ]; then
+   BUILD_AVOIDANCE_FLAG=0
+fi
+
+echo "BUILD_AVOIDANCE_FLAG=$BUILD_AVOIDANCE_FLAG"
 echo "CLEAN_FLAG=$CLEAN_FLAG"
 echo "EDIT_FLAG=$EDIT_FLAG"
 
-if [ "x$TARGETS" != "x  " ]; then
+if [ $BUILD_AVOIDANCE_FLAG -eq 1 ]; then
+    # Build Avoidance requested. Get URL of a usable context, if any.
+    export BUILD_AVOIDANCE_URL=$(get_build_avoidance_context)
+fi
+
+if [ "x$TARGETS" != "x$EMPTY_TARGETS" ]; then
    TARGETS_STD="$(find_targets centos_pkg_dirs)"
 
    BUILD_TYPE_SAVE="$BUILD_TYPE"
@@ -247,44 +296,50 @@ echo "EXTRA_ARGS_RPM='$EXTRA_ARGS_RPM'"
 echo "TARGETS='$TARGETS'"
 echo "TARGETS_STD='$TARGETS_STD'"
 echo "TARGETS_RT='$TARGETS_RT'"
+echo "TARGETS_INSTALLER='$TARGETS_INSTALLER'"
 echo "TARGETS_MISC='$TARGETS_MISC'"
 
 if [ $CLEAN_FLAG -eq 1 ]; then
+
+   if [ "x$TARGETS" == "x$EMPTY_TARGETS" ] && [ $BUILD_AVOIDANCE_FLAG -eq 1 ] ; then
+      build_avoidance_clean
+   fi
+
    if [ $STD_BUILD -eq 1 ]; then
-      if [ "x$TARGETS" == "x  " ] || [ "$TARGETS_STD" != " " ] || [ "$TARGETS_MISC" != " " ]; then
+      if [ "$TARGETS" == "$EMPTY_TARGETS" ] || [ "$TARGETS_STD" != "$EMPTY_TARGETS" ] || [ "$TARGETS_MISC" != "$EMPTY_TARGETS" ]; then
          if [ $EDIT_FLAG -ne 1 ]; then
             echo "${BUILD_PKGS_PARALLEL_DIR}/build-rpms-parallel --std --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_RPM $TARGETS_STD $TARGETS_MISC"
             ${BUILD_PKGS_PARALLEL_DIR}/build-rpms-parallel --std --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_RPM $TARGETS_STD $TARGETS_MISC || exit 1
 
          fi
       fi
-      if [ "x$TARGETS" == "x  " ] || [ "$TARGETS_STD" != " " ] || [ "$TARGETS_MISC" != " " ]; then
+      if [ "$TARGETS" == "$EMPTY_TARGETS" ] || [ "$TARGETS_STD" != "$EMPTY_TARGETS" ] || [ "$TARGETS_MISC" != "$EMPTY_TARGETS" ]; then
          echo "${BUILD_PKGS_PARALLEL_DIR}/build-srpms-parallel --std --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_SRPM $TARGETS_STD $TARGETS_MISC"
          ${BUILD_PKGS_PARALLEL_DIR}/build-srpms-parallel --std --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_SRPM $TARGETS_STD $TARGETS_MISC || exit 1
       fi
    fi
 
    if [ $RT_BUILD -eq 1 ]; then
-      if [ "x$TARGETS" == "x  " ] || [ "$TARGETS_RT" != " " ] || [ "$TARGETS_MISC" != " " ]; then
+      if [ "$TARGETS" == "$EMPTY_TARGETS" ] || [ "$TARGETS_RT" != "$EMPTY_TARGETS" ] || [ "$TARGETS_MISC" != "$EMPTY_TARGETS" ]; then
          if [ $EDIT_FLAG -ne 1 ]; then
             echo "${BUILD_PKGS_PARALLEL_DIR}/build-rpms-parallel --rt --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_RPM $TARGETS_RT $TARGETS_MISC"
             ${BUILD_PKGS_PARALLEL_DIR}/build-rpms-parallel --rt --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_RPM $TARGETS_RT $TARGETS_MISC || exit 1
          fi
       fi
-      if [ "x$TARGETS" == "x  " ] || [ "$TARGETS_RT" != " " ] || [ "$TARGETS_MISC" != " " ]; then
+      if [ "$TARGETS" == "$EMPTY_TARGETS" ] || [ "$TARGETS_RT" != "$EMPTY_TARGETS" ] || [ "$TARGETS_MISC" != "$EMPTY_TARGETS" ]; then
          echo "${BUILD_PKGS_PARALLEL_DIR}/build-srpms-parallel --rt --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_SRPM $TARGETS_RT $TARGETS_MISC"
          ${BUILD_PKGS_PARALLEL_DIR}/build-srpms-parallel --rt --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_SRPM $TARGETS_RT $TARGETS_MISC || exit 1
       fi
    fi
 
    if [ $INSTALLER_BUILD -eq 1 ]; then
-      if [ "x$TARGETS" == "x" ] || [ "$TARGETS_INSTALLER" != " " ]; then
+      if [ "$TARGETS" == "$EMPTY_TARGETS" ] || [ "$TARGETS_INSTALLER" != "$EMPTY_TARGETS" ]; then
          if [ $EDIT_FLAG -ne 1 ]; then
             echo "${BUILD_PKGS_PARALLEL_DIR}/build-rpms-serial --installer --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_RPM $TARGETS_INSTALLER"
             ${BUILD_PKGS_PARALLEL_DIR}/build-rpms-serial --installer --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_RPM $TARGETS_INSTALLER || exit 1
          fi
       fi
-      if [ "x$TARGETS" == "x  " ] || [ "$TARGETS_INSTALLER" != " " ]; then
+      if [ "$TARGETS" == "x$EMPTY_TARGETS" ] || [ "$TARGETS_INSTALLER" != "$EMPTY_TARGETS" ]; then
          echo "${BUILD_PKGS_PARALLEL_DIR}/build-srpms-serial --installer --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_SRPM $TARGETS_INSTALLER"
          ${BUILD_PKGS_PARALLEL_DIR}/build-srpms-serial --installer --clean $EXTRA_ARGS_COMMON $EXTRA_ARGS_SRPM $TARGETS_INSTALLER || exit 1
       fi
@@ -317,13 +372,22 @@ function launch_build()
    fi
 
    echo "Launching $build_type build, logging to $logfile"
-   \rm $logfile
+   if [ $APPEND_LOG_FLAG -eq 0 ] && [ -f $logfile ]; then
+       \rm $logfile
+   fi
+
 
    echo -e "\n######## $(date): Launching build-srpms-parallel --$build_type $EXTRA_ARGS $@\n" | tee --append $logfile
+
+   echo "BUILD_AVOIDANCE_URL=$BUILD_AVOIDANCE_URL" | tee --append $logfile
+   if [ "x$BUILD_AVOIDANCE_URL" != "x" ]; then
+      echo "build_avoidance $build_type" | tee --append $logfile
+      build_avoidance $build_type 2>&1 | tee --append $logfile
+   fi
+
    # No clean flag, call build-srpms-parallel followed by build-rpms-parallel
    echo "${BUILD_PKGS_PARALLEL_DIR}/build-srpms-parallel --$build_type $EXTRA_ARGS_COMMON $EXTRA_ARGS_SRPM $targets" | tee --append $logfile
    ${BUILD_PKGS_PARALLEL_DIR}/build-srpms-parallel --$build_type $EXTRA_ARGS_COMMON $EXTRA_ARGS_SRPM $targets 2>&1 | tee --append $logfile
-
    rc=${PIPESTATUS[0]}
    if [ $rc -eq 0 ]; then
       echo -e "\n######## $(date): build-srpm-parallel --$build_type was successful" | tee --append $logfile
@@ -371,9 +435,8 @@ fi
 echo "Capture build context"
 git_context > "${MY_WORKSPACE}/CONTEXT"
 
-
 if [ $STD_BUILD -eq 1 ]; then
-   if [ "x$TARGETS" == "x  " ] || [ "$TARGETS_STD" != " " ] || [ "$TARGETS_MISC" != " " ]; then
+   if [ "x$TARGETS" == "$EMPTY_TARGETS" ] || [ "$TARGETS_STD" != "$EMPTY_TARGETS" ] || [ "$TARGETS_MISC" != "$EMPTY_TARGETS" ]; then
       launch_build std
    else
       echo "Skipping 'std' build, no valid targets in list: $TARGETS"
@@ -383,7 +446,7 @@ else
 fi
 
 if [ $RT_BUILD -eq 1 ]; then
-   if [ "x$TARGETS" == "x  " ] || [ "$TARGETS_RT" != " " ] || [ "$TARGETS_MISC" != " " ]; then
+   if [ "x$TARGETS" == "$EMPTY_TARGETS" ] || [ "$TARGETS_RT" != "$EMPTY_TARGETS" ] || [ "$TARGETS_MISC" != "$EMPTY_TARGETS" ]; then
       launch_build rt
    else
       echo "Skipping 'rt' build, no valid targets in list: $TARGETS"
@@ -393,7 +456,7 @@ else
 fi
 
 if [ $INSTALLER_BUILD -eq 1 ]; then
-   if [ "x$TARGETS" == "x  " ] || [ "$TARGETS_INSTALLER" != " " ] || [ "$TARGETS_MISC" != " " ]; then
+   if [ "x$TARGETS" == "$EMPTY_TARGETS" ] || [ "$TARGETS_INSTALLER" != "$EMPTY_TARGETS" ] || [ "$TARGETS_MISC" != "$EMPTY_TARGETS" ]; then
       launch_build installer
    else
       echo "Skipping 'installer' build, no valid targets in list: $TARGETS"
@@ -402,6 +465,10 @@ else
    echo "Skipping 'installer' build"
 fi
 
+if [ $REFERENCE_BUILD -eq 1 ]; then
+    echo "Saving reference context"
+    build_avoidance_save_reference_context
+fi
 
 echo "All builds were successful"
 
