Build Avoidance
Purpose:
   Reduce build times after a repo sync by pulling in pre-generated
srpms and rpms and other build products created by a local reference build.

Usage:
  repo sync
  generate-cgcs-centos-repo.sh ...
  populate_downloads.sh ...
  build-pkgs --build-avoidance [--build-avoidance-user <user> \
     --build-avoidance-host <addr> --build-avoidance-dir <dir>]

Reference builds:
- A server performs a regular (daily?), automated builds using
  existing methods. Call these the reference builds.

- The builds are timestamped, and preserved for some time. (weeks?)
  The MY_WORKSPACE directory for the build shall have a common root
  directory, and a leaf directory that is a time stamp of format
  YYYY-MM-DD_hh-mm-ss.
  e.g.
  MY_WORKSPACE=/localdisk/loadbuild/jenkins/StarlingX/2018-07-19_11-30-21

- A build CONTEXT is captured, consisting of the SHA of each and every
  git that contributed to the build.

- For each package built, a file shall capture he md5sums of all the
  source code inputs to the build of that package.

- All these build products are accessible locally (e.g. a regional
  office) via rsync (other protocols can be added later).  ssh
  is also required to run remote query commands on the reference build.

- Location of the reference build can be specified via command line, or
  defaults can be put in $MY_REPO/local-build-data/build_avoidance_source.
  The local-build-data directory is gitignored by stx-root and so can be
  customized for local needs.
  e.g.
  cat $MY_REPO/local-build-data/build_avoidance_source
  BUILD_AVOIDANCE_USR="jenkins"
  BUILD_AVOIDANCE_HOST="stx-build-server.myco.com"
  BUILD_AVOIDANCE_DIR="/localdisk/loadbuild/jenkins/StarlingX"

Notes:
- Build avoidance is only used if requested.
- Build avoidance does not nesecarrily use the latest reference build.
  It compares the git context of all available reference builds vs your
  own git context, and chooses the most recent for which you gits have
  all the conent.  i.e. all your gits will be same or newer than that
  used by the reference build.  This also meens that some packages might
  still need to be rebuilt after the download step.
- Normally build avoidance remembers the last download context and will only
  consider reference builds newer than the last download.   You can reset
  using 'build-pkgs --build-avoidance --clear' to erase the download history.
  When might this matter to me?  If you change to an old branch that
  hasn't been synced recently and want to build in that context.
- The primary assumtion of Build Avoidance is that it is faster to
  download packages than to build them.  This is typically true of a
  good LAN, but likely not true of a WAN. This is why we emphasize the
  local nature of your reference build server.

Also in this update:
- reworked context generation to be relative to 'dirname $MY_REPO'
- Moved md5sum calculation to a common file, and fixed case where
  symlinks where canonacalized to paths outside of $MY_REPO.
  We'll make an exception to canonacalization to keep paths
  relative to $MY_REPO.
- In future other functions could be moved to the common file.

Story: 2002835
Task: 22754
Change-Id: I757780190cc6063d0a2d3ad9d0a6020ab5169e99
Signed-off-by: Scott Little <scott.little@windriver.com>

diff --git a/build-tools/build-pkgs-serial b/build-tools/build-pkgs-serial
--- a/build-tools/build-pkgs-serial
+++ b/build-tools/build-pkgs-serial
@@ -1,10 +1,22 @@
 #!/bin/bash
 
-# This program is a wrapper around build-srpms and build-rpms
+#
+# Copyright (c) 2018 Wind River Systems, Inc.
+#
+# SPDX-License-Identifier: Apache-2.0
+#
+
+#
+# Build first src.rpms, then rpms, from source, or from a downloaded tarball
+# or src.rpm plus our additional patches.
+#
+# This program is a wrapper around build-srpms-serial and build-rpms-serial
+#
 
 BUILD_PKGS_SERIAL_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}" )" )"
 
 source "${BUILD_PKGS_SERIAL_DIR}/git-utils.sh"
+source "${BUILD_PKGS_SERIAL_DIR}/build-avoidance-utils.sh"
 source "${BUILD_PKGS_SERIAL_DIR}/spec-utils"
 
 
@@ -13,14 +25,15 @@ usage () {
     echo "Usage: "
     echo "   Create source and Binary rpms:"
     echo "   Build optimizations (--no-descendants, --no-required, --no-build-info,"
-    echo "   --no-autoclean) are not recommended for the first build after a clone/pull,"
-    echo "   nor the final build prior to creating an iso or patch, but can be used"
-    echo "   for intermediate builds.  i.e. while debugging compilation failures." 
-    echo "      build-pkgs-serial [--no-descendants] [--no-required] [--no-build-info] [--no-autoclean] [--careful] [--formal] [ list of package names ]"
+    echo "   --no-autoclean, --no-build-avoidance) are not recommended for the first build"
+    echo "   after a clone/pull, nor the final build prior to creating an iso or patch,"
+    echo "   but can be used for intermediate builds."
+    echo "   i.e. while debugging compilation failures."
+    echo "      build-pkgs-serial [--build-avoidance | --no-build-avoidance] [--no-descendants] [--no-required] [--no-build-info] [--no-autoclean] [--careful] [--formal] [ list of package names ]"
     echo ""
     echo "   Delete source rpms, and the directories associated with it's creation:"
     echo "   Note: does not clean an edit environment"
-    echo "      build-pkgs-serial --clean [ list of package names ]"
+    echo "      build-pkgs-serial --clean [--build-avoidance | --no-build-avoidance] [ list of package names ]"
     echo ""
     echo "   Extract an src.rpm into a pair of git trees to aid in editing it's contents,"
     echo "   one for source code and one for metadata such as the spec file."
@@ -39,12 +52,17 @@ usage () {
 HELP=0
 CLEAN_FLAG=0
 EDIT_FLAG=0
+APPEND_LOG_FLAG=0
+BUILD_AVOIDANCE_FLAG=0
 STD_BUILD=1
 RT_BUILD=1
 INSTALLER_BUILD=0
 
+export BUILD_AVOIDANCE_URL=""
+
+
 # read the options
-TEMP=$(getopt -o h --long serial,rt,std,edit,no-meta-patch,no-descendants,no-required,no-build-info,no-autoclean,formal,careful,help,clean -n 'build-pkgs' -- "$@")
+TEMP=$(getopt -o h --long serial,rt,std,installer,edit,build-avoidance,no-build-avoidance,build-avoidance-dir:,build-avoidance-host:,build-avoidance-user:,build-avoidance-day:,no-meta-patch,no-descendants,no-required,no-build-info,no-autoclean,formal,careful,help,clean,append-log -n 'build-pkgs-serial' -- "$@")
 if [ $? -ne 0 ]; then
     usage
     exit 1
@@ -55,8 +73,21 @@ eval set -- "$TEMP"
 EXTRA_ARGS_COMMON=""
 EXTRA_ARGS_SRPM=""
 EXTRA_ARGS_RPM=""
+
+export BUILD_AVOIDANCE_OVERRIDE_DIR=""
+export BUILD_AVOIDANCE_OVERRIDE_HOST=""
+export BUILD_AVOIDANCE_OVERRIDE_USR=""
+export BUILD_AVOIDANCE_DAY=""
+
 while true ; do
     case "$1" in
+        --append-log)     APPEND_LOG_FLAG=1 ; shift ;;
+        --build-avoidance) BUILD_AVOIDANCE_FLAG=1 ; shift ;;
+        --no-build-avoidance) BUILD_AVOIDANCE_FLAG=0 ; shift ;;
+        --build-avoidance-dir)  BUILD_AVOIDANCE_OVERRIDE_DIR=$2; shift 2 ;;
+        --build-avoidance-host)  BUILD_AVOIDANCE_OVERRIDE_HOST=$2; shift 2 ;;
+        --build-avoidance-user)  BUILD_AVOIDANCE_OVERRIDE_USR=$2; shift 2 ;;
+        --build-avoidance-day) BUILD_AVOIDANCE_DAY=$2; shift 2 ;;
         --no-descendants) EXTRA_ARGS_COMMON+=" --no-descendants" ; shift ;;
         --formal)         EXTRA_ARGS_COMMON+=" --formal" ; shift ;;
         --careful)        EXTRA_ARGS_RPM+=" --careful" ; shift ;;
@@ -80,6 +111,50 @@ if [ $HELP -eq 1 ]; then
     usage
     exit 0
 fi
+
+function my_exit() {
+    build-rpms-parallel --std --tmpfs-clean
+    build-rpms-parallel --rt --tmpfs-clean
+}
+
+function my_sigint() {
+    echo "build-pkgs-parallel sigint"
+    pkill -SIGABRT -P $BASHPID &> /dev/null
+    echo "build-pkgs-parallel waiting"
+    wait
+    echo "build-pkgs-parallel wait complete"
+
+}
+
+function my_sighup() {
+    echo "build-pkgs-parallel sighup"
+    pkill -SIGABRT -P $BASHPID &> /dev/null
+    echo "build-pkgs-parallel waiting"
+    wait
+    echo "build-pkgs-parallel wait complete"
+}
+
+function my_sigabrt() {
+    echo "build-pkgs-parallel sigabrt"
+    pkill -SIGABRT -P $BASHPID &> /dev/null
+    echo "build-pkgs-parallel waiting"
+    wait
+    echo "build-pkgs-parallel wait complete"
+}
+
+function my_sigterm() {
+    echo "build-pkgs-parallel sigterm"
+    pkill -SIGABRT -P $BASHPID &> /dev/null
+    echo "build-pkgs-parallel waiting"
+    wait
+    echo "build-pkgs-parallel wait complete"
+}
+
+trap my_exit EXIT
+trap my_sigint INT
+trap my_sighup HUP
+trap my_sigabrt ABRT
+trap my_sigterm TERM
 
 TARGETS=" $@ "
 TARGETS_STD=" "
@@ -159,8 +234,18 @@ find_targets () {
    return 0
 }
 
+if [ $EDIT_FLAG -eq 1 ] || [ "x$TARGETS" != "x  " ]; then
+   BUILD_AVOIDANCE_FLAG=0
+fi
+
+echo "BUILD_AVOIDANCE_FLAG=$BUILD_AVOIDANCE_FLAG"
 echo "CLEAN_FLAG=$CLEAN_FLAG"
 echo "EDIT_FLAG=$EDIT_FLAG"
+
+if [ $BUILD_AVOIDANCE_FLAG -eq 1 ]; then
+    # Build Avoidance requested. Get URL of a usable context, if any.
+    export BUILD_AVOIDANCE_URL=$(get_build_avoidance_context)
+fi
 
 if [ "x$TARGETS" != "x  " ]; then
    TARGETS_STD="$(find_targets centos_pkg_dirs)"
@@ -207,6 +292,11 @@ echo "TARGETS_INSTALLER='$TARGETS_INSTALLER'"
 echo "TARGETS_MISC='$TARGETS_MISC'"
 
 if [ $CLEAN_FLAG -eq 1 ]; then
+
+   if [ "x$TARGETS" == "x  " ] && [ $BUILD_AVOIDANCE_FLAG -eq 1 ] ; then
+      build_avoidance_clean
+   fi
+
    if [ $STD_BUILD -eq 1 ]; then
       if [ "x$TARGETS" == "x  " ] || [ "$TARGETS_STD" != " " ] || [ "$TARGETS_MISC" != " " ]; then
          if [ $EDIT_FLAG -ne 1 ]; then
@@ -273,8 +363,18 @@ function launch_build()
    fi
 
    echo "Launching $build_type build, logging to $logfile"
+   if [ $APPEND_LOG_FLAG -eq 0 ] && [ -f $logfile ]; then
+       \rm $logfile
+   fi
 
    echo -e "\n######## $(date): Launching build-srpms-serial --$build_type $EXTRA_ARGS $@\n" | tee --append $logfile
+
+   echo "BUILD_AVOIDANCE_URL=$BUILD_AVOIDANCE_URL" | tee --append $logfile
+   if [ "x$BUILD_AVOIDANCE_URL" != "x" ]; then
+      echo "build_avoidance $build_type" | tee --append $logfile
+      build_avoidance $build_type 2>&1 | tee --append $logfile
+   fi
+
    # No clean flag, call build-srpms-serial followed by build-rpms-serial
    echo "${BUILD_PKGS_SERIAL_DIR}/build-srpms-serial --$build_type $EXTRA_ARGS_COMMON $EXTRA_ARGS_SRPM $targets" | tee --append $logfile
    ${BUILD_PKGS_SERIAL_DIR}/build-srpms-serial --$build_type $EXTRA_ARGS_COMMON $EXTRA_ARGS_SRPM $targets 2>&1 | tee --append $logfile
@@ -353,6 +453,11 @@ if [ $INSTALLER_BUILD -eq 1 ]; then
    fi
 else
    echo "Skipping 'installer' build"
+fi
+
+if [ $REFERENCE_BUILD -eq 1 ]; then
+    echo "Saving reference context"
+    build_avoidance_save_reference_context
 fi
 
 echo "All builds were successful"
diff --git a/build-tools/build-rpms-serial b/build-tools/build-rpms-serial
--- a/build-tools/build-rpms-serial
+++ b/build-tools/build-rpms-serial
@@ -6,6 +6,22 @@
 # SPDX-License-Identifier: Apache-2.0
 #
 
+# 
+# Builds rpm files from src.rpm files.
+#
+# This version compiles one package at a time.
+# 
+# The location of packages to be built is 
+# $MY_WORKSPACE/<build-type>/rpmbuild/SRPMS.
+#
+# The build order is a derived from the BuildRequires in the 
+# spec files in the src.rpms.  Note that the BuildRequires sometimes
+# create dependency loops, so no correct order can be computed.  In these
+# cases we add a retry loop.  As long as one new package builds, we
+# keep retrying the loop, until all are built, or no progress is made.
+# So please don't panic and CTRL-C just because you see a few error
+# messages go by!
+#
 
 export ME=$(basename "$0")
 CMDLINE="$ME $@"
@@ -63,12 +79,10 @@ create-no-clean-list () {
    if [ ! -f $NO_CLEAN_LIST_FILE ]; then
        NEED_REBUILD=1
    else
-       if [ -f MY_BUILD_CFG ]; then
-           if [ -f MY_BUILD_CFG ]; then
-               find "$MY_BUILD_CFG" -not -newermm "$NO_CLEAN_LIST_FILE" | grep -q $(basename $MY_BUILD_CFG)
-               if [ $? -eq 0 ]; then
-                   NEED_REBUILD=1
-               fi
+       if [ -f $MY_BUILD_CFG ]; then
+           find "$MY_BUILD_CFG" -not -newermm "$NO_CLEAN_LIST_FILE" | grep -q $(basename $MY_BUILD_CFG)
+           if [ $? -eq 0 ]; then
+               NEED_REBUILD=1
            fi
        fi
    fi
diff --git a/build-tools/build-srpms-parallel b/build-tools/build-srpms-parallel
--- a/build-tools/build-srpms-parallel
+++ b/build-tools/build-srpms-parallel
@@ -1,6 +1,26 @@
 #!/bin/bash
 # set -x
 
+#
+# Copyright (c) 2018 Wind River Systems, Inc.
+#
+# SPDX-License-Identifier: Apache-2.0
+#
+
+#
+# Create src.rpm files from source, or from a downloaded tarball
+# or src.rpm plus our additional patches.
+#
+# This version tries to compile many packages in parallel.
+#
+# The location of packages to be build are identified by
+# <distro>_pkg_dirs[_<opt-build-type>] files located at the root of
+# any git tree (e.g. istx/stx-integ/centos_pkg_dirs).
+#
+# The build of an individul package is driven by it's build_srpm.data
+# file plus a <pkg-name>.spec file or an srpm_path file.
+#
+
 export ME=$(basename "$0")
 CMDLINE="$ME $@"
 
@@ -9,6 +29,7 @@ source $BUILD_SRPMS_PARALLEL_DIR/git-utils.sh
 source $BUILD_SRPMS_PARALLEL_DIR/spec-utils
 source $BUILD_SRPMS_PARALLEL_DIR/srpm-utils
 source $BUILD_SRPMS_PARALLEL_DIR/classify
+source $BUILD_SRPMS_PARALLEL_DIR/build-srpms-common.sh
 
 
 INITIAL_DIR=$(pwd)
@@ -372,7 +393,7 @@ build_dir () {
          fi
 
          if [ "${ORIG_SRPM_PATH}x" == "x" ]; then
-            # handle mirror: definitions
+            # handle 3rd_party: definitions
             echo "$p" | grep "^3rd_party:" >/dev/null && ORIG_SRPM_PATH=$(echo $p | sed "s%^3rd_party:%$THIRD_PARTY_ROOT/%")
          fi
 
@@ -455,7 +476,7 @@ clean_srpm_dir () {
    local SRPM_OUT_NAME
    local INPUTS_TO_CLEAN=""
 
-   if [ $EXCLUDE_MD5 == "" ]; then
+   if [ "$EXCLUDE_MD5" == "" ]; then
        EXCLUDE_MD5=0
    fi
 
@@ -626,24 +647,15 @@ build_dir_srpm () {
       # Capture md5 data for all input files
       #
       local TARGET_SOURCES_DIR="$SOURCES_DIR/$TARGET_FOUND"
-      local INPUT_FILES="$TARGET_SOURCES_DIR/srpm_input.files"
-      local INPUT_FILES_SORTED="$TARGET_SOURCES_DIR/srpm_sorted_input.files"
       local INPUT_FILES_MD5="$TARGET_SOURCES_DIR/srpm_input.md5"
       local REFERENCE_MD5="$TARGET_SOURCES_DIR/srpm_reference.md5"
 
       mkdir -p "$TARGET_SOURCES_DIR"
-      find $PKG_BASE -type f > $INPUT_FILES
-      find $ORIG_SRPM_PATH -type f >> $INPUT_FILES
-         (
-         cd $PKG_BASE
-         if [ "x$COPY_LIST" != "x" ]; then
-            find $COPY_LIST -type f >> $INPUT_FILES
-         fi
-         )
-      cat $INPUT_FILES | xargs readlink -f | sort --unique > $INPUT_FILES_SORTED
-      \rm -f $INPUT_FILES
-      cat $INPUT_FILES_SORTED | xargs md5sum | sed "s# $(readlink -f $MY_REPO)/# #" > $INPUT_FILES_MD5
-      \rm -f $INPUT_FILES_SORTED
+      md5sums_from_input_vars "$SRC_BUILD_TYPE_SRPM" "$ORIG_SRPM_PATH" "$TARGET_SOURCES_DIR" > "$INPUT_FILES_MD5"
+      if [ $? -ne 0 ]; then
+         echo "ERROR: $FUNCNAME (${LINENO}): md5sums_from_input_vars '$SRC_BUILD_TYPE_SRPM' '$ORIG_SRPM_PATH' '$TARGET_SOURCES_DIR'"
+         return 1
+      fi
       echo "Wrote: $INPUT_FILES_MD5"
 
       #
@@ -946,38 +958,15 @@ build_dir_spec () {
          # Capture md5 data for all input files
          #
          local TARGET_SOURCES_DIR="$SOURCES_DIR/$TARGET_FOUND"
-         local INPUT_FILES="$TARGET_SOURCES_DIR/srpm_input.files"
-         local INPUT_FILES_SORTED="$TARGET_SOURCES_DIR/srpm_sorted_input.files"
          local INPUT_FILES_MD5="$TARGET_SOURCES_DIR/srpm_input.md5"
          local REFERENCE_MD5="$TARGET_SOURCES_DIR/srpm_reference.md5"
 
          mkdir -p "$TARGET_SOURCES_DIR"
-         find $PKG_BASE -type f > $INPUT_FILES
-         find $ORIG_SRPM_PATH -type f >> $INPUT_FILES
-            (
-            cd $PKG_BASE
-            if [ "x$SRC_DIR" != "x" ]; then
-               if [ -d "$SRC_DIR" ]; then
-                  find $SRC_DIR -type f | grep -v '[/][.]git$' | grep -v '[/][.]git[/]' >> $INPUT_FILES
-               fi
-            fi
-
-            if [ "x$COPY_LIST" != "x" ]; then
-               find $COPY_LIST -type f >> $INPUT_FILES
-            fi
-
-            if [ "x$COPY_LIST_TO_TAR" != "x" ]; then
-               find $COPY_LIST_TO_TAR -type f >> $INPUT_FILES
-            fi
-
-            if [ "x$OPT_DEP_LIST" != "x" ]; then
-               find $OPT_DEP_LIST -type f >> $INPUT_FILES 2> /dev/null
-            fi
-            )
-         cat $INPUT_FILES | xargs readlink -f | sort --unique > $INPUT_FILES_SORTED
-         \rm -f $INPUT_FILES
-         cat $INPUT_FILES_SORTED | xargs md5sum | sed "s# $(readlink -f $MY_REPO)/# #" > $INPUT_FILES_MD5
-         \rm -f $INPUT_FILES_SORTED
+         md5sums_from_input_vars "$SRC_BUILD_TYPE_SPEC" "$SPEC" "$TARGET_SOURCES_DIR" > "$INPUT_FILES_MD5"
+         if [ $? -ne 0 ]; then
+             echo "ERROR: $FUNCNAME (${LINENO}): md5sums_from_input_vars '$SRC_BUILD_TYPE_SPEC' '$SPEC' '$TARGET_SOURCES_DIR'"
+             return 1
+         fi
          echo "Wrote: $INPUT_FILES_MD5"
 
          #
