Capture the git context of the build
First step in build avoidance is the creation of a reference build.
We need to capture the state of all the git trees that contribute
to the reference build.

This update will save the git context to $MY_WORKSPACE/CONTEXT

The context file format is actually a shell script that can be run to
recreate the build context.

   repo init ...
   repo sync
   cd $MY_REPO/..
   source .../CONTEXT

Sample CONTEXT file ....
(cd ./cgcs-root && git checkout -f 12a159594130d75aedf40da3f3b1e6bd7f9ff375)
(cd ./cgcs-root/stx/git/calico && git checkout -f 12a159594130d75aedf40da3f3b1e6bd7f9ff375)
(cd ./cgcs-root/stx/git/ceilometer && git checkout -f 12a159594130d75aedf40da3f3b1e6bd7f9ff375)
...
(cd ./stx-tools && git checkout -f 12a159594130d75aedf40da3f3b1e6bd7f9ff375)
(cd ./.repo/manifests && git checkout -f 12a159594130d75aedf40da3f3b1e6bd7f9ff375)
(cd ./.repo/repo && git checkout -f 12a159594130d75aedf40da3f3b1e6bd7f9ff375)

This update also the git_list function, which populates the previously
introduced GIT_LIST variable, and can be used in several other code
paths where we want to find all gits in a directory tree.

Tested build/clean/edit  parallel/serial

Story: 2002835
Task: 22754
Change-Id: I5009b8a360bdb4a03e5a4e83430b7f2ef135115e
Signed-off-by: Scott Little <scott.little@windriver.com>

diff --git a/build-tools/build-pkgs-parallel b/build-tools/build-pkgs-parallel
--- a/build-tools/build-pkgs-parallel
+++ b/build-tools/build-pkgs-parallel
@@ -4,6 +4,7 @@
 
 BUILD_PKGS_PARALLEL_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}" )" )"
 
+source "${BUILD_PKGS_PARALLEL_DIR}/git-utils.sh"
 source "${BUILD_PKGS_PARALLEL_DIR}/spec-utils"
 
 
@@ -141,8 +142,7 @@ find_targets () {
    local RESULT=" "
    local FOUND=0
 
-   for g in $(find $MY_REPO -type d -name .git); do
-      d=$(dirname $g)
+   for d in $GIT_LIST; do
       if [ -f $d/$centos_pkg_dirs ]; then
          for d2 in $(grep -v '^#' $d/$centos_pkg_dirs); do
             name=""
@@ -364,7 +364,15 @@ function progbar()
 }
 
 # Create $MY_WORKSPACE if it doesn't exist already
-mkdir -p $MY_WORKSPACE
+mkdir -p "${MY_WORKSPACE}"
+if [ $? -ne 0 ]; then
+    echo "Failed to create directory '${MY_WORKSPACE}'"
+    exit 1
+fi
+
+echo "Capture build context"
+git_context > "${MY_WORKSPACE}/CONTEXT"
+
 
 if [ $STD_BUILD -eq 1 ]; then
    if [ "x$TARGETS" == "x  " ] || [ "$TARGETS_STD" != " " ] || [ "$TARGETS_MISC" != " " ]; then
